### ISSUE TITLE
User fix bug

### ISSUE THREAD

**Issue by SoobinJung1013** [team-e-techeer/schoolvery-be#64]
**🫧Describe the bug**
유저 API 부분 버그 수정

**Comment by JoeCP17** [comment]
user delete , modify user 버그 발견완료 

< User delete > 
- 오류내용 
 return 값이 null로 되어있어 삭제가 되었더라도 확인이 불가능 

-조치 
String 값으로 변환하여 삭제되었을 시, 삭제가 완료되었습니다 텍스트 출력

< User update > 
- 오류내용 
service 값이 null로 설정되어 있음 + return 값이 하나는 dto , 하나는 entity로 설정되어있음 

- 조치 
return 값을 하나로 통일 시켜 다시 재 작업 + 현재 닉네임과 휴대폰만 수정이 가능하기 때문에 다른내용도 추가적으로 수정진행할 예정

**Comment by JoeCP17** [comment]
<img width="714" alt="스크린샷 2022-05-30 오전 11 41 01" src="https://user-images.githubusercontent.com/76832303/170907415-29f3b7fc-6a10-422b-833a-3a8972955aa2.png">

update bug 수정 완료
